### ISSUE TITLE
strange rgb effects

### ISSUE THREAD

**Issue by jdfosterarmy** [tgraupmann/ChromaTwitchExtension#1]
hi, im running version 0.0.0.8

when ever i am sending chroma from sending rgb effects to the receiving twitch account, it keeps sending the game's effects along with some random colors.  I did the test on multiple games and it keeps doing the same thing.

how i did the test. on my desktop, i have the stream effects on through one twitch account. then on my laptop, i am logged into an alternate twitch account. it receives the data, but its doing this to all my receiving devices.

**Comment by tgraupmann** [comment]
This is due to a change in the ChromaSDK. This is fixed in the new official version which you can grab from the Microsoft Store for free. You can find the widget here - https://www.microsoft.com/store/apps/9PG8DNKL06M6

https://youtu.be/Uv17xAoWpPo
